ALTER TABLE runs 
ADD COLUMN worker_id TEXT,
ADD COLUMN last_heartbeat_at TIMESTAMPTZ,
ADD COLUMN attempt_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN max_retries INTEGER NOT NULL DEFAULT 3,
ADD COLUMN base_delay_ms INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN max_delay_ms INTEGER NOT NULL DEFAULT 60000,
ADD COLUMN next_retry_at TIMESTAMPTZ,
ADD COLUMN last_error TEXT;

